import { test, expect } from '@playwright/test';
test.beforeEach(async ({ page }) => {
  // Keep browser checks offline from the real analytics service.
  await page.route('https://cloud.umami.is/script.js', route => route.fulfill({ contentType: 'application/javascript', body: '' }));
});
test('dark mode follows system then preserves explicit choice across languages', async ({ page }, testInfo) => {
  await page.emulateMedia({colorScheme:'dark'});
  await page.goto('/');
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  const toggle = page.getByRole('button', {name:'Dark mode'});
  await expect(toggle).toHaveAttribute('aria-pressed','true');
  await toggle.click();
  await expect(page.locator('html')).toHaveAttribute('data-theme','light');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme','light');
  await toggle.focus();
  await page.keyboard.press('Enter');
  await page.locator('[data-language-switch]').click();
  await expect(page.getByRole('button',{name:'ডার্ক মোড'})).toHaveAttribute('aria-pressed','true');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:testInfo.outputPath('dark-bangla.png'),fullPage:true});
  await page.getByRole('navigation').getByRole('link',{name:'সংগ্রহশালা'}).click();
  await page.locator('a[href="/bn/archive/a-language-for-resistance/"]').click();
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
});
test('Bangla switch translates pages and preserves locale and section', async ({ page }, testInfo) => {
  await page.goto('/works/');
  await page.locator('[data-language-switch]').click();
  await expect(page).toHaveURL('/bn/works/');
  await expect(page.locator('html')).toHaveAttribute('lang', 'bn');
  await expect(page.locator('h1')).toContainText('কথোপকথনে ছবি');
  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href','https://labanijangi.com/bn/works/');
  expect((await page.locator('body').innerText()).replace('English','')).not.toMatch(/[a-zA-Z]{2,}/);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.goto('/bn/');
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path:testInfo.outputPath('bangla-home.png'), fullPage:true });
  await expect(page.locator('#roots-title')).toHaveText('নদীআর নদিয়া।');
  await expect(page.locator('.district-home title')).toHaveText('নদিয়া');
  await page.getByRole('navigation').getByRole('link',{name:'সংগ্রহশালা'}).click();
  await page.locator('a[href="/bn/archive/a-language-for-resistance/"]').click();
  await expect(page).toHaveURL('/bn/archive/a-language-for-resistance/');
  await expect(page.locator('h1')).toHaveText('প্রতিরোধের ভাষা');
  await expect(page.locator('time')).toContainText('২০২৫');
  await expect(page.locator('.prose')).toContainText('সৌম্যদীপ');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('lang','bn');
  await page.locator('[data-language-switch]').click();
  await expect(page).toHaveURL('/archive/a-language-for-resistance/');
  await expect(page.locator('h1')).toHaveText('A Language for Resistance');
  await page.goto('/bn/404/');
  await expect(page.getByRole('link',{name:'প্রথম পাতায় ফিরুন'})).toHaveAttribute('href','/bn/');
});
test('analytics configuration is production-only and event links remain usable', async ({ page }) => {
  await page.goto('/contact/');
  const tracker = page.locator('script[data-website-id]');
  await expect(tracker).toHaveCount(1);
  await expect(tracker).toHaveAttribute('data-website-id', 'c0819d04-f244-4caf-8922-e89e57123ae6');
  await expect(tracker).toHaveAttribute('data-domains', 'labanijangi.com,www.labanijangi.com');
  await expect(page.locator('.contact-button')).toHaveAttribute('data-umami-event', 'instagram-click');
  await page.goto('/archive/');
  await expect(page.locator('.source-row[data-umami-event]')).toHaveCount(3);
  await page.locator('a[href="/archive/a-language-for-resistance/"]').click();
  await expect(page.locator('h1')).toHaveText('A Language for Resistance');
  await expect(page.locator('script[data-website-id]')).toHaveCount(1);
});
test('home, navigation and published archive work without layout overflow', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page).toHaveTitle(/Labani Jangi/);
  await expect(page.locator('h1')).toContainText('Labani');
  await expect(page.locator('.bengal-map .district')).toHaveCount(23);
  await expect(page.locator('.bengal-map .district-home')).toHaveAttribute('data-district-id', 'nadia');
  await page.screenshot({ path: testInfo.outputPath('home.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('navigation').getByRole('link', {name:'About'}).click();
  await expect(page).toHaveURL('/about/');
  await page.goto('/archive/');
  await page.locator('a[href="/archive/a-language-for-resistance/"]').click();
  await expect(page.locator('h1')).toHaveText('A Language for Resistance');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href','https://labanijangi.com/archive/a-language-for-resistance/');
  expect(errors).toEqual([]);
});
test('sitemap and missing page', async ({ page, request }) => {
  const sitemap = await request.get('/sitemap.xml');
  expect(await sitemap.text()).toContain('https://labanijangi.com/archive/a-language-for-resistance/');
  expect(await sitemap.text()).toContain('https://labanijangi.com/bn/privacy/');
  await page.goto('/404.html');
  await expect(page.getByRole('link', {name:'Return to the home page'})).toBeVisible();
});

test('sharing and legal pages have complete localized metadata', async ({ page }) => {
  await page.goto('/privacy/');
  await expect(page).toHaveTitle('Privacy policy — Labani Jangi');
  await expect(page.locator('meta[property="og:image"]')).toHaveAttribute('content', 'https://labanijangi.com/social-card.png');
  await expect(page.locator('link[rel="manifest"]')).toHaveAttribute('href', '/site.webmanifest');
  await expect(page.locator('main')).toContainText('Umami');
  await page.goto('/bn/terms/');
  await expect(page.locator('html')).toHaveAttribute('lang', 'bn');
  await expect(page.locator('main')).toContainText('ব্যবহারের শর্তাবলি');
});
